export const columnsData = [
  "Action",
  "Building",
  "Floor",
  "Unit",
  "Asset Name",
  "OEM Name",
  "Asset Number",
  "Equipment Id",
  "Serial Number",
  "Model Number",
  "Group",
  "Sub Group",
  "Critical",
  "Capacity",
  "Purchase Date",
  "Purchase Cost",
  "Status",
  "Created On",
  "Updated On",
  "W Start",
  "W Expiry",
  "Installation Date",
  "Meter Configured",
  "Supplier",
];

// export const serviceColumns = [
//   "Action",
//   "ID",
//   "Service Name",
//   "Service Code",
//   "Reference Number",
//   "Category",
//   "Group",
//   "UOM",
//   "Site",
//   "Floor",
//   "Building",
//   "Area",
//   "Status",
//   "Model Number",
//   "Created On",
// ];
