export const stateCityModal: Record<string, string[]> = {
  AndhraPradesh: ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Tirupatis"],
  ArunachalPradesh: ["Itanagar", "Tawang", "Pasighat", "Ziro", "Bomdila"],
  Assam: ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Tezpur"],
  Bihar: ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga"],
  Chhattisgarh: ["Raipur", "Bilaspur", "Durg", "Korba", "Jagdalpur"],
  Goa: ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"],
  Gujarat: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar"],
  Haryana: ["Chandigarh", "Gurgaon", "Faridabad", "Panipat", "Ambala"],
  HP: ["Shimla", "Manali", "Dharamshala", "Solan", "Mandi"],
  Jharkhand: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar"],
  Karnataka: ["Bengaluru", "Mysuru", "Mangaluru", "Hubballi", "Belagavi"],
  Kerala: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kannur"],
  MP: ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain"],
  Maharashtra: ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad"],
  Manipur: ["Imphal", "Churachandpur", "Thoubal", "Bishnupur", "Ukhrul"],
  Meghalaya: ["Shillong", "Tura", "Jowai", "Cherrapunjee", "Baghmara"],
  Mizoram: ["Aizawl", "Lunglei", "Champhai", "Serchhip", "Kolasib"],
  Nagaland: ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha"],
  Odisha: ["Bhubaneswar", "Cuttack", "Rourkela", "Puri", "Berhampur"],
  Punjab: ["Amritsar", "Ludhiana", "Patiala", "Jalandhar", "Bathinda"],
  Rajasthan: ["Jaipur", "Jodhpur", "Udaipur", "Ajmer", "Kota"],
  Sikkim: ["Gangtok", "Namchi", "Pelling", "Ravangla", "Geyzing"],
  Tamil_Nadu: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"],
  Telangana: ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam"],
  Tripura: ["Agartala", "Dharmanagar", "Udaipur", "Kailashahar", "Ambassa"],
  Uttarakhand: ["Dehradun", "Haridwar", "Rishikesh", "Nainital", "Almora"],
  UP: ["Lucknow", "Kanpur", "Varanasi", "Agra", "Prayagraj"],
  West_Bengal: ["Kolkata", "Darjeeling", "Howrah", "Durgapur", "Asansol"],
  Delhi: ["New Delhi", "Dwarka", "Saket", "Rohini", "Karol Bagh"],
  Andaman_Nicobar_Islands: ["Port Blair", "Havelock", "Diglipur"],
  Chandigarh: ["Chandigarh"],
  Daman_Diu: ["Silvassa", "Daman", "Diu", "Vapi"],
  Lakshadweep: ["Kavaratti", "Agatti", "Andrott", "Amini", "Minicoy"],
  Puducherry: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
  JK: ["Srinagar", "Jammu", "Baramulla", "Pulwama", "Anantnag"],
  Ladakh: ["Leh", "Kargil"],
};
